apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: be-geomaps-python
  name: be-geomaps-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-geomaps-python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be-geomaps-python
    spec:
      containers:
      - image: razeonex/geomaps-python:v0.0.3
        name: geomaps-python
        resources: {}
status: {}